### ISSUE TITLE
NPE in the incorrect instruction => code

### ISSUE THREAD

**Issue by danchanka** [lsfusion/plugin-idea#43]
Copy-paste this code:

    CLASS wA;
    f = DATA DATE (wA); 
    a IS wA => f(a);

Null pointer exception is thrown. Call stack:

```
java.lang.NullPointerException
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:174)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:180)
	at com.lsfusion.util.LSFPsiUtils.getContextParams(LSFPsiUtils.java:136)
	at com.lsfusion.lang.psi.references.impl.LSFAbstractParamReferenceImpl.getContextParams(LSFAbstractParamReferenceImpl.java:37)
	at com.lsfusion.lang.psi.references.impl.LSFAbstractParamReferenceImpl.resolveNoCache(LSFAbstractParamReferenceImpl.java:66)
	at com.lsfusion.lang.psi.LSFResolver.resolve(LSFResolver.java:31)
	at com.lsfusion.lang.psi.LSFResolver.resolve(LSFResolver.java:25)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:150)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:98)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:239)
	at com.lsfusion.lang.psi.references.impl.LSFReferenceImpl.multiResolveDecl(LSFReferenceImpl.java:101)
	at com.lsfusion.lang.psi.references.impl.LSFReferenceImpl.resolveDecl(LSFReferenceImpl.java:93)
	at com.lsfusion.lang.psi.references.impl.LSFReferenceImpl.resolve(LSFReferenceImpl.java:86)
	at com.lsfusion.lang.psi.references.impl.LSFReferenceImpl.isReferenceTo(LSFReferenceImpl.java:76)
	at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:38)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.lambda$execute$0(PsiSearchHelperImpl.java:773)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:138)
	at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:225)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.execute(PsiSearchHelperImpl.java:769)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$1.processInReadAction(PsiSearchHelperImpl.java:195)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl$1.processInReadAction(PsiSearchHelperImpl.java:179)
	at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:28)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:973)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadActionProcessor.process(ReadActionProcessor.java:28)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$0(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$1(JobLauncherImpl.java:111)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:122)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:57)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.bulkProcessElementsWithWord(PsiSearchHelperImpl.java:203)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processSingleRequest(PsiSearchHelperImpl.java:946)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processRequests(PsiSearchHelperImpl.java:607)
	at com.intellij.psi.search.SearchRequestQuery.processResults(SearchRequestQuery.java:31)
	at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:66)
	at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:70)
	at com.intellij.util.MergeQuery.forEach(MergeQuery.java:43)
	at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:55)
	at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:45)
	at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:68)
	at com.intellij.find.findUsages.FindUsagesHandler.findReferencesToHighlight(FindUsagesHandler.java:171)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(IdentifierHighlighterPass.java:173)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:150)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.lambda$highlightTargetUsages$0(IdentifierHighlighterPass.java:207)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightTargetUsages(IdentifierHighlighterPass.java:206)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:98)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by ichavchavadze** [comment]
Can't reproduce
